### ISSUE TITLE
Retrieving Documents with Embed Structure

### ISSUE THREAD

**Issue by rodrigomurta** [zbjornson/MongoDBLink#1]
Today if I insert a document with embed structures like:
`InsertDocument[coll, {"a" -> {"b" -> {"c" -> 1}, "d" -> {"e" -> 1}}}]`
when I try to retrieve it using `FindDocuments[coll]`I get:
`{{_id->56940b53f99bf4d2e3f258a0,a->Removed[JavaObject1473478154780673]}}`
In the command line the data is inserted ok.
By the way, amazing package.

**Comment by zbjornson** [comment]
Working on a fix right now, thanks for reporting this!

**Comment by rodrigomurta** [comment]
Tks for your fast reply. Will help me a lot.
