### ISSUE TITLE
Inserting Documents with list of Objects

### ISSUE THREAD

**Issue by rodrigomurta** [zbjornson/MongoDBLink#2]
This command is not working:
`InsertDocument[coll,{"company"->1,"entity"->{{"name"->"testName","value"->2}}}]`
It's not accepting list of objects.
**Update**
I just discovered that, If I already have a structure like:
`{"company"->1,"entity"->{{"name"->"testName","value"->2}}}`
in my collection, It's not deserialised when I retrieve it. I get:
`{_id->5694199377a827,company->1.,entity->{«JavaObject[com.mongodb.BasicDBObject]»}}`

**Comment by zbjornson** [comment]
Splitting out the update into a separate issue.

**Comment by rodrigomurta** [comment]
Now it's working perfectly.
Thanks a lot
